### ISSUE TITLE
[19.3] Unity Package Manager Error upon opening Project

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/EndlessRunnerSampleGame#13]
- Attempt to open the project in 19.3.0f1
- You will receive the following dialogue while the project is importing:

![image](https://user-images.githubusercontent.com/29916701/69630267-bb097080-1044-11ea-8c5a-1e75d4832046.png)

Retry won't work, and pressing Continue will lead to the project opening with a package error about the com.unity.render-pipelines.lightweight package.

Presumably it needs to be changed to com.unity.render-pipelines.universal

This does not prevent the game from running however

**Comment by UnityGuillaume** [comment]
Was fixed in latest master push, changed to universal

**Comment by Jacekpapapolski** [comment]
Fixed in ce97e09 - Closing!
