### ISSUE TITLE
[19.3] Characters appear too high on Main Menu

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/EndlessRunnerSampleGame#14]
Open up the project in 2019.3.0f1, navigate to the Start scene, and enter Play Mode.

Click Start button which will load you into the Main Menu

At this point you'll note that something seems wrong....
![15a7c46165053e26a06b88e40aa7b5f2](https://user-images.githubusercontent.com/29916701/69637311-4e946e80-1050-11ea-9417-a8eda1f50c0e.png)

The characters are positioned much above their original point, floating in mid-air, covering up some of the menu options. 
In addition, the bottom of the menu seems to have shifted upwards too.

**Comment by UnityGuillaume** [comment]
Should be fixed in latest master push

**Comment by Jacekpapapolski** [comment]
Fixed in a52a325 - Closing!
