### ISSUE TITLE
[19.3] Warnings in console upon opening project

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/EndlessRunnerSampleGame#15]
Open the Project in 19.3.0f1

You will note the following two warnings in the Start Scene:

- Component of type GUI Layer is no longer available in Unity. References to it will be removed!
- Component at index 2 could not be loaded when loading game object 'Main Camera'. Removing it!

However, the Main Camera game object doesn't have any Missing components, warnings, etc.
The Start scene renders and plays correctly however.

**Comment by UnityGuillaume** [comment]
After latest commit this seems to don't happen anymore even when cleaning the library folder and relaunching, I think it may have been linked to the broken package? (issue #13 )

**Comment by Jacekpapapolski** [comment]
I'm still getting a warning when Reimporting All, deleting the library folder, etc.
Was getting both warnings until the Library clear, but now it's just the:

Component of type GUI Layer is no longer available in Unity. References to it will be removed!

@UnityGuillaume

**Comment by Jacekpapapolski** [comment]
Fixed in 3980b1b - Closing!
