### ISSUE TITLE
UI Elements not visible in Scene View

### ISSUE THREAD

**Issue by rafayali** [Unity-Technologies/EndlessRunnerSampleGame#23]
All UI elements have only their colliders visible when viewing in Scene tab where as they are visible in game tab. Is there something which needs to be changed in order to make them visible? All layers are set to visible including UI layer. 

Using 2020.1.6f.

<img width="1552" alt="Screenshot 2020-10-05 at 7 45 09 PM" src="https://user-images.githubusercontent.com/1373965/95096248-7743c500-0745-11eb-9c36-22a1fefded81.png">
<img width="1552" alt="Screenshot 2020-10-05 at 8 02 05 PM" src="https://user-images.githubusercontent.com/1373965/95096418-ace8ae00-0745-11eb-8e0a-9b25c64d18be.png">
<img width="359" alt="Screenshot 2020-10-05 at 8 00 01 PM" src="https://user-images.githubusercontent.com/1373965/95096285-80cd2d00-0745-11eb-9a5e-2926233791e4.png">

**Comment by Ammar-Keshta** [comment]
Did you find a solution? I have the same problem!

**Comment by rafayali** [comment]
Sadly no.

**Comment by neitron** [comment]
In my case, the issue was the URP asset. I render all the renderers (including UI) with the render feature components. So I have set up "Nothing" for the Filtering->Transparent Layer Mask in the URP asset. It's unity bug
https://issuetracker.unity3d.com/issues/urp-canvas-becomes-invisible-in-the-scene-view-when-the-layer-that-canvas-is-in-is-disabled-in-the-transparent-layer-mask-list

**Comment by neitron** [comment]
![image](https://user-images.githubusercontent.com/10614636/136818643-a421d6c1-7a45-4ecc-84c1-cffad487c490.png)

**Comment by BindingForceDev** [comment]
> 

You just saved my butt with this! I was messing with these settings and must have deselected UI under Transparent Layer Mask!  I kept finding the toggle UI Layer visibility fix, but this is exactly the problem I had.

Thanks for the good work!

**Comment by ochrish** [comment]
I still had this same problem. The fix you guys posted, firstly I had no idea where to look for those settings. However, what fixed it for me is changing the canvas settings

![Screenshot 2022-06-09 195600](https://user-images.githubusercontent.com/78628026/172964389-0babb5f4-d128-4b6a-b765-78ecb64ca75f.png)
.
Change the render settings as shown.
Add your main camera
then set the layer to be above the rest

Hope this helps anyone else!
