### ISSUE TITLE
[Mac] 2019.1.0b10 Addressables runtime data with a different build target

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/EndlessRunnerSampleGame#6]
Open up the project on a Mac running 19.1

Open the Scene "Start"

You'll notice several UI elements missing, the cat from Trash Dash is pink and an error is in the console:

Addressables - runtime data was built with a different build target.  Expected StandaloneOSX, but data was built with StandaloneWindows64.  Certain assets may not load correctly including shaders.  You can rebuild player content via the Addressable Assets window.
UnityEngine.ResourceManagement.Util.DelayedActionManager:LateUpdate()

<img width="226" alt="ae253aee348f95bfb5e37f785b4b9fe5" src="https://user-images.githubusercontent.com/29916701/55472837-fc0bcb00-5604-11e9-8db1-0c4108b3c0df.png">

**Comment by UnityGuillaume** [comment]
Could have been caused by the addressable being in packed mode and data on the repo being build for windows.

I switched over to virtual mode for the addressable system in editor and removed the ServerData build (because they aren't needed) so it should work now.

**Comment by Jacekpapapolski** [comment]
Fixed as of dd62897 - Game now runs fine on Mac.
