### ISSUE TITLE
Going back to Main Menu after dying doesn't show your character

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/EndlessRunnerSampleGame#9]
Start and lose a run in Trash Dash

Upon being presented with your death screen click on the Main Menu button to go back to the Main Menu

Your character won't be displayed in the screen:

https://gyazo.com/d9ef9bdc9614410620d5505687919f5f

**Comment by Jacekpapapolski** [comment]
Character now appears in the main menu but always too high and above where he should be:

https://gyazo.com/40d1e093242a4e7609fdb2a4bc60a624

**Comment by UnityGuillaume** [comment]
@Jacekpapapolski Hum can't repro here, it's placed properly even if returning to menu from the pause menu or after game over...

Any special repro? or happen every time?

**Comment by Jacekpapapolski** [comment]
Hmm was happening every time but now that I've reopened the project it seems fine

Is my PC cursed?
I'll keep an eye for it but closing for now
